<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'album/album/delete' => __DIR__ . '/view/album/album/delete.phtml',
    'album/album/add'    => __DIR__ . '/view/album/album/add.phtml',
    'album/album/index'  => __DIR__ . '/view/album/album/index.phtml',
    'album/album/edit'   => __DIR__ . '/view/album/album/edit.phtml',
    'app/paginator'   => __DIR__ . '/../application/view/partial/paginator.phtml',
);
