<?php

// module/Blog/view/album/album/edit.phtml:

$title = 'Edit album';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="container">
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url(
        'album',
        array(
            'action' => 'edit',
            'id'     => $this->id,
        )
    ));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('title'));
    echo $this->formRow($form->get('artist'));
    echo $this->formRow($form->get('status'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>
</div>